### ISSUE TITLE
When a new note is created, shouldn't the program unpin the current daily note and pin the new one?

### ISSUE THREAD

**Issue by APJB2019** [jamiefdhurst/obsidian-auto-periodic-notes#21]

**Comment by jamiefdhurst** [comment]
Yes, this is already marked as something to work on within #19 - I'll close this issue as a duplicate.

**Comment by jamiefdhurst** [comment]
@APJB2019 Just to let you know, I've implemented this feature and it's released in version 0.2.0 (through PR #23) which should be available to download/update in Obsidian now.
